In [1]:
#hiddencell
from pbl_tools import *

# 스테이지 4

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.    
numpy는 자주 사용하는 라이브러리이므로 축약어인 np로 불러와 주세요. 

In [2]:
___ numpy ___ np

In [3]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

### Inst.

이 코드는 NumPy 라이브러리(Library)를 축약어인 np로 불러오는 기법입니다.

### Hint.
np는 numpy의 약칭입니다.   
import 와 as를 이용해서 numpy 라이브러리(Library)를 불러와주세요.

### Solution.
```python
import numpy as np
```

# 2.1차원 배열(array) 생성하기

In [4]:
jump_num = np.array([1,2,3,4])
same_num = np.array([2,2,2,2])

In [5]:
#checkcode
#empty

### Inst.
해당 코드는 각각 jump_num과 same_num이라는 두 개의 NumPy 배열을 생성하는 코드입니다.  

jump_num 배열은 [1,2,3,4]라는 **1차원 배열** 을 생성하며,   
same_num 배열은 [2,2,2,2]라는 **1차원 배열** 을 생성합니다.

NumPy 배열은 리스트(list)와는 달리 **모든 원소가 같은 데이터 타입** 을 가져야 합니다.     
이러한 특징은 배열의 원소를 다룰 때 더욱 **빠른 연산** 이 가능하게 해줍니다.  





### Hint.
empty

### Solution.
empty

# 3.NumPy 배열(array)간 덧셈(+) 연산하기

In [6]:
jump_num + same_num

array([3, 4, 5, 6])

In [7]:
#checkcode
#empty

### Inst.

해당 코드는 NumPy 배열의 **연산** 을 보여주는 코드입니다.  

jump_num과 same_num 두 개의 NumPy 배열이 있습니다.   
이 **두 배열은 크기가 같습**니다. 

<img width="282" src="https://drive.google.com/uc?id=15KoXz5npjcnAweBDlWn-4fO2zvtqKszi">

jump_num + same_num은 **두 배열의 같은 위치의 원소를 더한 새로운 배열** 을 반환합니다.     
첫 번째 원소는 **jump_num의 첫 번째 원소 1** 과 **same_num의 첫 번째 원소 2를** 더한 값인 **3** 이 됩니다.  

따라서 위 코드의 결과는 **[3, 4, 5, 6]** 입니다.  

### Hint.
empty

### Solution.
empty

# 4.NumPy 배열(array)간 뺄셈(-) 연산하기

In [8]:
jump_num - same_num

array([-1,  0,  1,  2])

In [9]:
#checkcode
#empty

### Inst.
<img width="282" src="https://drive.google.com/uc?id=14sYxBMuM-leBbkbAhRcZkiSzhuOTTx-v">

jump - same_num은 **두 배열의 같은 위치의 원소를 뺀 새로운 배열** 을 반환합니다.  
즉, 1에서 2를 빼면 -1, 2에서 2를 빼면 0, 3에서 2를 빼면 1, 4에서 2를 빼면 2가 됩니다.  
 
따라서 위 코드의 결과는 **[-1, 0, 1, 2]** 입니다.

이처럼 NumPy 배열은 같은 크기를 가진 배열끼리 연산이 가능하며, 같은 인덱스에 있는 원소끼리 연산이 수행됩니다.

### Hint.
empty

### Solution.
empty

# 5.NumPy 배열(array)간 곱셈(*) 연산하기

In [10]:
jump_num * same_num

array([2, 4, 6, 8])

In [11]:
#checkcode
#empty

### Inst.

<img width="282" src="https://drive.google.com/uc?id=1Cbs70jSnV_Lo43BmkBmmo68nK5VoGDjn">

jump_num * same_num은 **두 배열의 같은 위치의 원소를 곱한 새로운 배열** 을 반환합니다.  
즉, 1에서 2를 곱하면 2, 2에서 2를 곱하면 4, 3에서 2를 곱하면 6, 4에서 2를 곱하면 8이 됩니다.  

따라서 위 코드의 결과는 **[2, 4, 6, 8]** 입니다.

이러한 연산은 머신러닝에서 많이 사용되는데,   
예를 들어 이미지 데이터를 다룰 때 각 **픽셀의 색상값을 곱** 해서 **다양한 필터링 기법** 을 적용하거나,   
벡터의 방향을 결정하는데 사용됩니다.   
NumPy 배열을 이용하면 이러한 계산을 간단하게 수행할 수 있습니다.

### Hint.
empty

### Solution.
empty

# 6.NumPy 배열(array)간 거듭제곱(**) 연산하기

In [12]:
jump_num ** same_num

array([ 1,  4,  9, 16])

In [13]:
#checkcode
#empty

### Inst.

해당 코드는 NumPy 배열 jump_num과 same_num의 **원소 간 거듭제곱 연산**을 수행하는 코드입니다.

<img width="282" src="https://drive.google.com/uc?id=1i508eMFa8nl5Qj1lYAfb5LhyugQZVwXz">

NumPy 배열에서의 원소 간 연산은 각 원소들끼리 **일대일 대응으로 연산이 수행** 되며, 이때 연산자를 사용하여 수행됩니다.     
해당 코드에서는 `**` 연산자를 사용하여 jump_num 배열과 same_num 배열 간 **원소 간 거듭제곱 연산** 이 수행됩니다.  

코드를 실행하면, jump_num 배열과 same_num 배열의 첫 번째 원소인 **1과 2가 거듭제곱 연산** 으로 계산되어   
1의 2승인 1이 배열의 첫 번째 원소로 반환됩니다.   
이후 두 번째, 세 번째, 네 번째 원소들에 대해서도 같은 방식으로 거듭제곱 연산이 수행되어 결과 배열이 반환됩니다.

### Hint.
empty

### Solution.
empty

# 7.NumPy 배열(array)간 나눗셈(/) 연산하기

In [14]:
jump_num / same_num

array([0.5, 1. , 1.5, 2. ])

In [15]:
#checkcode
#empty

### Inst.

해당 코드는 NumPy 배열 jump_num과 same_num을 **나누는 연산** 을 수행하는 코드입니다.

<img width="282" src="https://drive.google.com/uc?id=10lUhkzgMR5dLf1J3t31q6JlLpbIphOHI">

`/` 기호는 NumPy 배열 간의 원소별(divide) 연산을 수행합니다.   
코드를 실행하면, jump_num 배열과 same_num 배열의 첫 번째 원소인 **1과 2가 나누기 연산** 으로 계산되어   
1 나누기 2인 0.5가 배열의 첫 번째 원소로 반환됩니다.   
이후 두 번째, 세 번째, 네 번째 원소들에 대해서도 같은 방식으로 나누기 연산이 수행되어 결과 배열이 반환됩니다.

### Hint.
empty

### Solution.
empty

# 8.NumPy 배열간 비교(<) 연산하기


In [16]:
random_num = np.array([2,5,4,6]) 
same_three_num = np.array([3,3,3,3]) 

random_num < same_three_num 

array([ True, False, False, False])

In [17]:
#checkcode
#empty

### Inst.

해당 코드는 NumPy 배열의 원소들 간 **비교 결과(True, False)** 를 반환하는 코드입니다.  

`<` 연산자는 NumPy 배열에서도 사용할 수 있으며, **원소 간 대소 비교** 를 수행합니다.    
따라서 random_num < same_three_num은 random_num 배열과 same_three_num 배열의 원소들을 각각 비교하여,  
동일한 인덱스의 원소끼리 대소를 비교한 결과(True, False)를 반환합니다.  

<img width="282" src="https://drive.google.com/uc?id=1adkhNgyZJWFN5KV6KmG0KTRjlQUYQq07">

해당 코드에서는 random_num 배열의 **첫 번째 원소는 2** 이고, same_three_num 배열의 **첫 번째 원소는 3**입니다.   
따라서 random_num < same_three_num의 **첫 번째 결과는 True** 가 됩니다.     
이러한 방식으로 나머지 원소들도 비교를 수행하며,  
결과적으로 **[True, False, False, False]** 가 반환됩니다.  

이러한 비교 연산은 데이터 분석에서 필요한 여러 가지 작업에서 사용됩니다.   
예를 들어, 데이터 프레임에서 **특정 조건에 맞는 데이터를 추출** 할 때 유용하게 사용됩니다.

### Hint.
empty

### Solution.
empty

# 9.2차원 배열(array) 생성하기

In [18]:
two_jump_num = np.array([[4,6],
                         [12,10]])
two_same_num = np.array([[2,2],
                         [2,2]])

In [19]:
#checkcode
#empty

### Inst.
지금까지 배운 배열의 연산을 실습해봅시다.

해당 코드는 두 개의 2x2 배열을 생성하는 코드입니다.

two_jump_num 배열은 2x2 크기의 배열로, 4개의 원소를 가지고 있습니다.  
이 배열의 각 원소는 4, 6, 12, 10으로 구성되어 있습니다.  

two_same_num 배열은 2x2 크기의 배열로, 4개의 원소를 가지고 있습니다.  
이 배열의 각 원소는 2로 구성되어 있습니다.

### Hint.
empty

### Solution.
empty

# 10.2차원 배열(array) 연산 실습(1)

[문제 2]  
위에서 생성한 two_jump_num 과 two_same_num을 곱한 후 two_jump_num을 더해보세요.
그 값을 a 변수에 할당해 주세요.

In [20]:
a =
print(a)

array([[12, 18],
       [36, 30]])

In [21]:
#checkcode
ensure_vals(globals(),'a')
@check_safety
def check(user_answer=a):
    if (user_answer[0] == [12, 18]).all():
        return True
    else:
        return False
check()

True

### Inst.
`*` 연산자는 NumPy 배열에서 각 원소별로 곱셈을 수행하며,  
 `+` 연산자는 각 원소별로 덧셈을 수행합니다.


### Hint.
위에서 배운 연산기호를 이용해 보세요. `(+,-,/,*,**)`

### Solution.
```python
a = two_jump_num * two_same_num + two_jump_num
a
```

# 11.2차원 배열(array) 연산 실습(2)

[문제 3]  
위에서 생성한 two_jump_num와 two_same_num 을 나눈 후 two_jump_num을 곱해보세요.

array([[ 8., 18.],
       [72., 50.]])

In [34]:
#checkcode
ensure_vals(globals(),'two_jump_num','two_same_num')
@check_safety
def check(user_answer=_):
    if (user_answer==two_jump_num / two_same_num * two_jump_num).all():
        return True
    else:
        return False
check()

True

### Inst.

`/` 연산자는 NumPy 배열에서 각 원소별로 나누기를 수행하며,  
`*` 연산자는 각 원소별로 곱셈을 수행합니다.

### Hint.
위에서 배운 연산기호를 이용해 보세요. `(+,-,/,*,**)`

### Solution.
```python
two_jump_num / two_same_num * two_jump_num
```

# 12.2차원 배열(array) 연산 실습(3)

[문제 4]  
`>` 왼쪽에는 two_same_num에 two_jump_num을 거듭제곱한 값을,   
`>` 오른쪽에는 two_jump_num 과 two_same_num을 곱한 값을 채워주세요.  

아래의 빈칸을 채워주세요.

In [24]:
___ > ___

array([[ True,  True],
       [ True,  True]])

In [25]:
#checkcode
ensure_vals(globals(),'two_same_num','two_jump_num')
@check_safety
def check(user_answer=_):
    if (sum(_) == ([2, 2])).all():
        return True
    else:
        return False
check()

True

### Inst.
`**` 연산자는 NumPy 배열에서 각 원소별로 거듭제곱을 수행하며,  
`*` 연산자는 각 원소별로 곱셈을 수행합니다.

### Hint.
위에서 배운 연산기호를 이용해 보세요. `(+,-,/,*,**)`

### Solution.
```python
two_same_num ** two_jump_num > two_jump_num * two_same_num 
```