In [ ]:
#hiddencell
from pbl_tools import *

# 스테이지 5

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.    
numpy는 자주 사용하는 라이브러리이므로 축약어인 np로 불러와 주세요. 

In [ ]:
___ numpy ___ np

In [ ]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

### Inst.
이 코드는 NumPy 라이브러리(Library)를 축약어인 np로 불러오는 기법입니다.

### Hint.
np는 numpy의 약칭입니다.   
import 와 as를 이용해서 numpy 라이브러리(Library)를 불러와주세요.

### Solution.
```python
import numpy as np
```

# 2.2차원 배열(array) 생성하기

In [ ]:
twelve_array = np.array([[3,4,5,4],
                         [1,5,6,7],
                         [9,2,6,4]])

twelve_array

array([[3, 4, 5, 4],
       [1, 5, 6, 7],
       [9, 2, 6, 4]])

In [ ]:
#checkcode
#empty

### Inst.
twelve_array는 NumPy의 `array()` 함수를 사용하여, **3행 4열의 2차원 배열을 생성** 한 코드입니다.   

각 행(row)은 `[]`로 둘러싸인 구조를 갖고 있으며, 쉼표(,)로 구분된 원소를 가지고 있습니다.  
각 행의 원소 개수는 4개이며, 총 12개의 원소를 가진 배열입니다.  

---

#### 결과 해석

코드 실행결과 **[[3, 4, 5, 4], [1, 5, 6, 7], [9, 2, 6, 4]]** 가 반환됩니다.

### Hint.
empty

### Solution.
empty

# 3.NumPy 배열(array)에서 최댓값(max) 찾기

In [ ]:
np.max(twelve_array)

9

In [ ]:
#checkcode
#empty

### Inst.
```python
twelve_array = np.array([[3,4,5,4],
                         [1,5,6,7],
                         [9,2,6,4]])
```
해당 코드는 NumPy의 `max()` 함수를 사용하여 **배열에서 가장 큰 값을 반환** 하는 파이썬 코드입니다.

`max()` 함수는 인자로 배열을 받아 해당 배열에서 가장 큰 값을 찾아 반환합니다.  
따라서 np.max(twelve_array)는 twelve_array 배열에서 가장 큰 값을 반환합니다.

---

#### 결과 해석

위 코드에서 twelve_array는 3행 4열의 2차원 배열입니다.   
`max()` 함수는 이 배열에서 가장 큰 값인 **9** 를 반환합니다.

### Hint.
empty

### Solution.
empty

# 4.NumPy 배열(array)에서 최솟값(min) 찾기

[문제 2]  
twelve_array 배열에서 가장 작은 값을 반환해보세요.  
아래 빈칸을 채워보세요.

In [ ]:
np.___(twelve_array)

1

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    if (user_answer==np.min(twelve_array)):
        return True
    else:
        return False
check()

False

### Inst.
`min()` 함수는 인자에 배열을 받아 해당 배열에서 가장 작은 값을 반환합니다.

---

#### 결과 해석

위 코드에서 twelve_array는 3행 4열의 2차원 배열입니다.   
`min()` 함수는 이 배열에서 가장 큰 작은 값인 **1** 을 반환합니다.

### Hint.
np.min()

### Solution.
```python
np.min(twelve_array)
```

# 5.NumPy 배열의 축(axis)을 기준으로 최댓값 구하기

In [ ]:
np.max(twelve_array, axis = 0)

array([9, 5, 6, 7])

In [ ]:
#checkcode
#empty


### Inst.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/75363345/221075468-6aac70f7-7aaf-4b58-a663-ad01fc64e43a.png">


stage2에서 axis(축)에 대해서 배웠습니다. 기억이 나시나요?   
최댓값을 구해볼 twelve_array 배열은 2차원 배열입니다.   

해당 코드는 NumPy의 `max()` 함수를 사용하여 twelve_array 배열의 **수직 방향에** 서 **가장 큰 값** 을 찾아 반환하는 코드입니다.   
`axis` 매개변수를 사용하여 **연산 방향**을 지정할 수 있으며,   
`axis=0`은 **수직** 방향, `axis=1`은 **수평** 방향입니다.

위 코드에서 `axis=0`은 **수직 방향으로 최댓값** 을 구하므로,   
twelve_array 배열의 첫 번째 열에서 가장 큰 값,   
두 번째 열에서 가장 큰 값, ... ,   
마지막 열에서 가장 큰 값으로 이루어진 배열을 반환합니다.

<img width="350" src="https://drive.google.com/uc?id=1zp3C3R4oMdLIbg5P6OJIxgd35_5XR9LB">


---

#### 결과 해석

코드 실행 결과 **[9, 5, 6, 7]** 이 반환됩니다.

### Hint.
empty

### Solution.
empty

# 6.NumPy 배열의 축(axis)을 기준으로 최솟값(min) 구하기

[문제 3]  
twelve_array 에서 각 **수평 방향** 의 최솟값을 구해보세요.  
아래 빈칸을 채워보세요.

In [ ]:
np.___(twelve_array, axis = ___)

array([3, 1, 2])

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    check1 = 3 in _
    check2 = 1 in _
    check3 = 2 in _
    if check1 and check2 and check3:
        return True
    else:
        return False
check()

True

### Inst.
`min()` 함수는 인자로 배열을 받아 해당 배열에서 가장 작은 값을 찾아 반환합니다.   
`axis`를 지정하면 지정한 축의 최솟값을 구할 수 있습니다.  
`axis=0`은 **수직** 방향, `axis=1`은 **수평** 방향입니다.  

---

#### 결과 해석

코드 실행 결과 **[3, 1, 2]** 가 반환됩니다.

### Hint.
`min()`, `axis = 1` 함수를 사용하면 수평 방향의 최솟값을 구할 수 있습니다.

### Solution.
```python
np.min(twelve_array, axis = 1)
```

# 7.NumPy 배열의 전체 원소 합(sum) 구하기

In [ ]:
np.sum(twelve_array)

56

In [ ]:
#checkcode
#empty

### Inst.

`sum()` 함수는 주어진 배열의 **모든 원소의 합** 을 반환합니다.   
이 때, 함수 인자로 axis를 지정하여 축 방향으로 계산할 수도 있습니다.   
만약 axis를 지정하지 않으면 **전체 배열의 합** 을 계산합니다.

`np.sum(twelve_array)`는 NumPy의 sum() 함수를 사용하여 배열 twelve_array의 모든 **원소의 합** 을 계산하는 코드입니다.  
즉, 해당 코드에서는 twelve_array 배열의 모든 요소들의 합을 반환하기 때문에,     
`sum()` 함수는 3+4+5+4+1+5+6+7+9+2+6+4 = 56을 반환합니다.  

`sum()` 함수는 NumPy에서 자주 사용되며, 데이터 분석, 머신러닝 등에서 배열의 합을 계산할 때 유용하게 사용됩니다.

---

#### 결과 해석
코드 실행 결과 twelve_array 배열의 **전체 원소의 합** 인 56이 반환됩니다.  

### Hint.
empty

### Solution.
empty

# 8.NumPy 배열의 각 수평 방향의 합(sum) 구하기
[문제 4]  
twelve_array 에서 각 수평 방향의 합계를 구해보세요.  
아래 빈칸을 채워보세요.

In [ ]:
np.___(___, axis = ___)

array([16, 19, 21])

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    if (user_answer==np.sum(twelve_array, axis =1)).all():
        return True
    else:
        return False
check()

True

### Inst.
`sum()` 함수는 주어진 배열의 모든 원소의 합을 반환합니다.   
`axis`를 지정하면 지정한 축의 최솟값을 구할 수 있습니다.    
`axis=0`은 **수직** 방향, `axis=1`은 **수평** 방향입니다.

<img width="350" src="https://drive.google.com/uc?id=16p7AcxiEQi3KkB59oE1Dl5FkfQZbXINB">

---

#### 결과 해석
코드 실행 결과 twelve_array 배열의 수평방향의 합 **[16, 19, 21]** 이 반환됩니다.  

### Hint.
`sum, axis = 1` 함수를 사용하면 수평 방향의 합을 구할 수 있습니다.

### Solution.
```python
np.sum(twelve_array, axis = 1)
```