In [1]:
#hiddencell
from pbl_tools import *

# 스테이지 2

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.  
numpy는 자주 사용하는 라이브러리(Library)이므로 축약어인 np로 불러와 주세요.

In [3]:
import ___ as np

In [4]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

### Inst.

이 코드는 NumPy 라이브러리(Library)를 축약어인 np로 불러오는 기법입니다.

### Hint.
np는 numpy의 약칭입니다.   
import 와 as를 이용해서 numpy 라이브러리(Library)를 불러와주세요.

### Solution.
```python
import numpy as np
```

# 2.다양한 차원(dimension)의 NumPy 배열 생성하기

In [5]:
one_dimension = np.ones(3)
print("---1차원 벡터---\n",one_dimension)

two_dimension = np.zeros((2,3))
print("\n---2차원 행렬---\n",two_dimension)

three_dimension = np.ones((2,3,2))
print("\n---3차원 텐서---\n",three_dimension)

---1차원 벡터---
 [1. 1. 1.]

---2차원 행렬---
 [[0. 0. 0.]
 [0. 0. 0.]]

---3차원 텐서---
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#checkcode
#empty

### Inst.
stage1에서 언급했듯이, NumPy의 핵심 객체는 **다차원 배열(array)** 입니다.   
데이터는 대개 숫자들의 배열로 표현되므로, **숫자로 배열된 데이터를 처리**하는 것은 매우 중요한 과정입니다.  
NumPy는 이러한 **다차원 배열을 처리** 하는 데 있어 강력한 기능을 제공합니다  

이번 스텝에서는 **차원(Dimension)에** 대해서 배워봅시다.   
차원을 쉽게 이해하기 위해 그림으로 표현해 보았습니다.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/75363345/221068717-36293173-7cf5-444f-9a98-1785c13a1a0d.png">

NumPy에서 1차원 배열은 **벡터(vector)**,  
2차원 배열은 **행렬(matrix)**,     
3차원 이상의 배열은 **텐서(tensor)** 라고 부릅니다. 

해당 코드는 NumPy 라이브러리(Library)를 사용하여 **다차원 배열을 생성하고 출력**하는 코드입니다. 
   
다차원 배열은 데이터를 효율적으로 다룰 수 있기 때문에 인공지능 분야에서 많이 사용됩니다.   
해당 코드를 사용하면 다차원 배열을 생성하고 해당 배열을 이용하여 인공지능 모델을 구현할 수 있습니다.  

---

#### 결과 해석
one_dimension 변수는 크기가 3인 **1차원 벡터(vector)** ,   
two_dimension 변수는 크기가 2x3인 **2차원 행렬(matrix)** ,   
three_dimension 변수는 크기가 2x3x2인 **3차원 텐서(tensor)** 가 생성되었습니다. 

### Hint.
empty

### Solution.
empty

# 3.1차원 배열(array) 생성하기

In [6]:
np.array([1,2,3])


array([1, 2, 3])

In [ ]:
#checkcode
#empty

### Inst.
이번엔 **axis(축)** 에 대해서 살펴보도록 하겠습니다.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/75363345/221082390-69c21d15-358f-4809-bd35-5f8515607454.png">

**1차원 배열**은 **1개의 축(axis)** 을 갖는 배열입니다.     
따라서 행(row)과 열(column)의 개념이 없습니다.     

해당 코드는 NumPy의 `array()` 함수를 사용하여 1차원 배열(array)을 생성하는 파이썬 코드입니다.  
NumPy의 `array()` 함수는 **파이썬 리스트(list)를 입력받아 NumPy 배열을 반환** 합니다.  
이 함수를 사용하여 **다양한 차원의 배열을 생성** 할 수 있으며, 생성된 배열은 **다양한 수학적 연산 및 함수를 사용하여 처리** 할 수 있습니다.  

해당 코드에서 출력된 값은 1부터 3까지의 요소가 하나의 축을 따라 **벡터(vector) 형태** 로 나열된 배열임을 확인할 수 있습니다.       
이러한 특징으로 인해 **1차원 배열은 벡터 연산** 에 자주 사용됩니다.    

---

#### 결과 해석
크기가 3인 **1차원 배열** 이 출력되었습니다.

### Hint.
empty

### Solution.
empty

# 4.2차원 배열(array) 생성하기

In [7]:
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#checkcode
#empty

### Inst.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/75363345/221075468-6aac70f7-7aaf-4b58-a663-ad01fc64e43a.png">

**2차원 배열** 은 **2개의 축(axis)** 을 갖는 배열입니다.   
따라서 **행(row)과 열(column)의 개념이 존재** 합니다.   

해당 코드는 NumPy의 `array()` 함수를 사용하여 2차원 배열(array)을 생성하는 파이썬 코드입니다.  
배열의 축(axis)은 각각 0과 1로 지정될 수 있으며, **axis=0은 수직 방향, axis=1은 수평 방향** 으로 연산이 적용됩니다.      

해당 코드에서 출력된 결과는 2개의 행과 3개의 열을 갖는 **행렬(matrix) 형태** 로 나열된 배열임을 확인할 수 있습니다.         
이러한 특징으로 인해 **2차원 배열은 벡터 연산**에 매우 유용하게 사용되며, 데이터 처리 및 분석에서도 자주 활용됩니다.       

---

#### 결과 해석
크기가 2x3인 **2차원 배열** 이 출력되었습니다.

### Hint.
empty

### Solution.
empty

# 5.3차원 배열(array) 생성하기

In [8]:
np.array([[[1,2],
           [3,4],
           [5,6]],
           [[7,8],
           [9,10],
           [11,12]]])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
#checkcode
#empty

### Inst.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/75363345/221083181-0c3544d3-a1ec-418e-8fa3-55a932207d2f.png">

**3차원 배열**은 3개의 축(axis)을 갖는 배열입니다.   
따라서 **깊이(depth), 행(row), 열(column)** 의 개념이 존재합니다.  

해당 코드는 NumPy의 array() 함수를 사용하여 3차원 배열(array)을 생성하는 파이썬 코드입니다.       
배열의 축(axis)은 0, 1, 2와 같이 각 차원마다 지정할 수 있으며,     
**axis=0은 깊이(depth) 방향, axis=1은 수직 방향, axis=2는 수평 방향** 으로 연산이 적용됩니다.  

해당 코드에서 출력된 결과는 깊이, 행, 열이 존재하는 3차원 배열로, 깊이는 2개, 행은 3개, 열은 2개의 요소를 가지고 있습니다.     
이러한 특징으로 인해 **3차원 배열**은 **딥러닝 모델에서 이미지, 음성** 등 다양한 형태의 데이터 처리에 매우 유용하게 사용됩니다.  

---

#### 결과 해석
크기가 2x3x2인 **3차원 배열** 이 출력되었습니다.

### Hint.
empty

### Solution.
empty

# 6.2차원 배열(array) 생성하기 실습

[문제 2]  
NumPy의 `zeros()` 함수를 사용해서, 행이 2개이고 열이 3개인 
모든 요소가 **0으로 초기화된 행렬** 을 만들어보세요.         
아래 빈칸을 채워주세요.

In [9]:
np.zeros((___))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check0 = user_answer.shape == (2,3)
    check1 = 0 in user_answer
    
    if check0 and check1: 
        return True
    else:
        return False
check()

True

### Inst.
`zeros()` 함수는 새로운 배열을 생성하고, 모든 요소를 0으로 초기화합니다.     
`zeros()` 함수의 인자로는 배열의 크기를 지정하는 튜플(tuple)이나 정수(int)를 입력할 수 있습니다.

---

#### 결과 해석
크기가 2x3인 **2차원 배열** 이 출력되었습니다.

### Hint.
np.zeros(행,열)

### Solution.
```python
np.zeros((2,3))
```

# 7.3차원 배열(array) 생성하기 실습

[문제 3]  
NumPy의 ones() 함수를 사용해서, 깊이 2개, 행이 3개, 열이 4개인 모든 요소가 **1로 초기화된 텐서** 를 만들어보세요.  
아래 빈칸을 채워주세요.

In [12]:
np.___((___))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check0 = user_answer.shape == (2,3,4)
    check1 = 1 in user_answer
    
    if check0 and check1: 
        return True
    else:
        return False
check()

True

### Inst.
`ones()` 함수는 지정한 크기의 새로운 배열을 생성하고, 모든 요소를 1로 초기화합니다.     
`ones()` 함수의 인자로는 배열의 크기를 지정하는 튜플(tuple)이나 정수(int)를 입력할 수 있습니다.  

---

#### 결과 해석
크기가 2x3x4인 **3차원 배열** 이 출력되었습니다.

### Hint.
`np.ones(깊이, 행, 열)`

### Solution.
```python
np.ones((2,3,4))
```